version: "3.2"

services:
  flask_server:
    build: ./fact-bounty-flask
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./log_horizon.db
        target: /fact-bounty-flask/log_horizon.db
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///fact-bounty-flask/log_horizon.db

  client:
    build: ./fact-bounty-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
